### ISSUE TITLE
❓Custom plugins details

### ISSUE THREAD

**Issue by 98max1** [FooBallZ/pulsar#35]
**Question**
Sorry, wasn't sure where to post this.
Can you elaborate a bit more about how and what these custom plugins are used for.
From my understanding you set up a plugin and while scanning a domain, the bash code runs and if it  provides any output you get the set vulnerability score assigned to that domain.

**Comment by 0x0FB0** [comment]
Hi @98max1,

Custom plugins are additional checks made during the **active scan** mode.
In order to run a custom check (plugin) you need to create one in django admin dashboard and it will be executed during the next active scan. 
During creation you will get a commentary of an example syntax. In short, custom plugins are bash scripts runned per domain basis. 
At each execution, additional *DOM_SVCS* and *DOM_FQDN* environmental variables are set for creative usage.

*DOM_SVCS* variable is in a form of coma sepparated list of port/service i.e `DOM_SVC=22/SSH,80/HTTP,8080/HTTP`
*DOM_FQDN* is just a fully qualified domain name.

Custom plugin will trigger a new vulnerability entry upon any output of your script, so it is crucial to either filter out interesting patterns via the `grep` utility, or manually `echo` the interesting output to stdout.

Example script:
```
#!/bin/bash
echo $DOM_SVC | tr "," "\n" | grep HTTP | cut -d "/" -f 1 | while read svc
do curl "http://${DOM_FQDN}:${svc}/vuln.php" 2>&1 | grep VULNERABILITY
done
```

Basic lunix commands and utilities such as curl or openssl are already available in sandbox, if you would like to use more advanced tool, you need to install them on sandbox container manually by editing `sandbox_storage/Dockerfile` and rebuilding it with `docker-compose build sandbox --no-cache`

Let me know if you have further questions/problems.
